config/routes.rb
Rails.application.routes.draw do
  # ESTO DEBE ESTAR ARRIBA DE TODO, PARA DARLE PRIORIDAD
  namespace :authentication, path: '', as: '' do # Con 'path' vacio no tenemos que poner 'authentication' en la url, y con 'as' vacio no tenemos que poner 'authentication_users_new' sino 'users_new'
    resources :users, only: [:new, :create], path: '/register', path_names: { new: '/' }
    resources :sessions, only: [:new, :create, :destroy], path: '/login', path_names: { new: '/' }
  end

  resources :favorites, only: [:index, :create, :destroy], param: :product_id

  resources :users, only: :show, path: '/user', param: :username

  resources :categories, except: :show # Quitamos la opcion show
  
  # delete '/products/:id', to: 'products#destroy'
  # post '/products', to: 'products#create'
  # patch '/products/:id', to: 'products#update'
  # get '/products/new', to: 'products#new', as: :new_product
  # get '/products/:id/edit', to: 'products#edit', as: :edit_product
  # get '/products', to: 'products#index'
  # get '/products/:id', to: 'products#show', as: :product
  resources :products, path: '/' # Con esto podemos obviar las lineas anteriores al usar la convencion de nombres por defecto de rails, 
                                 # y con path: '/' hacemos que /products resida en /
end

app/models/product.rb
class Product < ApplicationRecord
    include PgSearch::Model
    pg_search_scope :search_full_text, against: {
        title: 'A',
        description: 'B'
    } # Las letras indican la prioridad en la busqueda

    has_one_attached :photo # Para guardar fotos usamos has_one_attached :nombre_que_queramos

    validates :title, presence: true
    validates :description, presence: true
    validates :price, presence: true

    has_many :favorites, dependent: :destroy

    belongs_to :category # Un producto pertenece a una categoria (claves foraneas)
    belongs_to :user # Un producto pertenece a un usuario (claves foraneas)
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
    skip_before_action :protect_pages, only: [:index, :show] # Aqui saltamos la proteccion de la pagina para ciertas acciones

    def index
        @categories = Category.all.load_async
        # @products = Product.all.with_attached_photo # Con with_attached_photo evitamos las consultas innecesarias que se hacen a la BD

        # # Filtrado por categorias
        # if params[:category_id]
        #     @products = @products.where(category_id: params[:category_id]) # Extendemos la query anterior
        # end

        # if params[:min_price].present? # Con present? comprobamos que el parametro contiene valor, porque se va enviar aunque este vacio 
        #     @products = @products.where('price >= ?', params[:min_price]) # Aqui el '?' es parecido a PHP
        # end

        # if params[:max_price].present?
        #     @products = @products.where('price <= ?', params[:max_price])
        # end

        # if params[:query_text].present?
        #     @products = @products.search_full_text(params[:query_text])
        # end

        # if params[:order_by].present?
        #     order_by = {
        #         newest: 'created_at DESC',
        #         expensive: 'price DESC',
        #         cheapest: 'price ASC'
        #     }.fetch(params[:order_by]&.to_sym, 'created_at DESC') # Recibimos un string por parametros, con to_sym lo convertimos a simbolo
        #     # order[params[:order_by]] Esto hace los mismo que el fetch anterior, pero el fetch nos ofrece la posibilidad de introducir un valor por defecto (created_at DESC), incluso el bloque IF no seria necesario

        #     @products = @products.order(order_by).load_async # ATENCION: Solo puede haber un order en cada consulta, asegurate de que no tienes ningun order en las consultas anteriores
        #                                                      # Ademas el metodo load_async siempre tiene que ir al final
        # end

        # @pagy, @products = pagy_countless(@products, items: 12)

        # Todo lo anterior lo refactorizamos asi. El archivo esta en app > queries > find_products.rb
        @pagy, @products = pagy_countless(FindProducts.new.call(product_params_index).load_async, items: 12)
    end

    def show
        product
    end

    def new
        @product = Product.new
    end

    def create
        @product = Current.user.products.new(product_params) # Rails es suficientemente inteligente para recoger los productos de cada usuario. Automaticamente asigna el nuevo producto al usuario  con la sesion iniciada

        if @product.save
            redirect_to products_path, notice: t('.created')
        else
            render :new, status: :unprocessable_entity
        end
    end

    def edit
        authorize! product # Metodo creado en application_controller.rb
    end

    def update
        authorize! product # Metodo creado en application_controller.rb

        if product.update(product_params) # Aqui quitamos el @ y asi llamamos al metodo producto creado mas abajo y se le aplica el update directamente
            redirect_to products_path, notice: t('.updated')
        else
            render :edit, status: :unprocessable_entity
        end
    end

    def destroy
        authorize! product # Metodo creado en application_controller.rb

        product.destroy # Aqui quitamos el @ y asi llamamos al metodo producto creado mas abajo y se le aplica el destroy directamente

        redirect_to products_path, notice: t('.destroyed'), status: :see_other # Siempre que haya una peticion DELETE con turbo, debemos pasarle -> status: :see_other
    end

    private
    def product_params
        params.require(:product).permit(:title, :description, :price, :photo, :category_id)
    end

    def product_params_index
        params.permit(:category_id, :min_price, :max_price, :query_text, :order_by, :page, :favorites)
    end

    def product
        @product = Product.find(params[:id]) # En ruby, la ultima sentencia se corresponde con el return
    end
end

app/views/products/edit.html.erb
<h2><%= t('.title') %></h2>

<%= render 'shared/form' %>

app/views/products/index.html.erb
<%= turbo_frame_tag 'home' do %>

    <%= form_with url: products_path, method: :get do |form| %>
        <%= form.text_field :query_text, placeholder: t('.query_text'), onChange: 'this.form.requestSubmit()', value: params[:query_text], class: 'w-full my-2 rounded-2xl border-gray-200' %>

        <div class='flex'>
            <%= form.number_field :min_price, placeholder: t('.min_price'), onChange: 'this.form.requestSubmit()', value: params[:min_price], class: 'w-1/3 rounded-2xl border-gray-200' %> <!-- Con value hacemos que el parametro se quede en la caja y no cambie al hacer la peticion -->
            <%= form.number_field :max_price, placeholder: t('.max_price'), onChange: 'this.form.requestSubmit()', value: params[:max_price], class: 'w-1/3 rounded-2xl border-gray-200 mx-2' %>

            <%= form.select :order_by, options_for_select([[t('.newest'), 'newest'], [t('.expensive'), 'expensive'], [t('.cheapest'), 'cheapest']], params[:order_by]), {}, { onChange: 'this.form.requestSubmit()', class: 'w-1/3 rounded-2xl border-gray-200 text-gray-500' } %> <!-- El options_for_select tiene varias formas de pasar los valores, consultalas en la documentacion -->
        </div>
    <% end %>

    <div class='flex overflow-x-scroll gap-2 my-4'>
        <%= render(CategoryComponent.new) %>

        <%= render(CategoryComponent.with_collection(@categories)) %>
    </div>

    <%= turbo_frame_tag :products, class: 'flex flex-col m-2' do %>
        <%= turbo_frame_tag "products-#{@pagy.page}", class: 'products flex flex-col w-full sm:flex-row sm:flex-wrap sm:gap-x-2' do %> <!-- CUIDADO: hay que usar las comillas dobles -->
            <%= render partial: 'shared/product', collection: @products %> <!-- En el partial ponemos lo que habia dentro del bucle, y esto ya genera el bucle automaticamente con collection -->
            <%= turbo_frame_tag "products-#{@pagy.next}", class: 'products flex flex-col w-full sm:flex-row sm:flex-wrap sm:gap-x-2', src: pagy_url_for(@pagy, @pagy.next), loading: :lazy if @pagy.next %> <!-- Hacemos la paginacion infinita. Con el if, nos evitamos la ultima peticion a una pagina que no existe -->
        <% end %>
    <% end %>
    
<% end %>

app/views/products/new.html.erb
<%= turbo_frame_tag 'modal' do %>
  <div data-controller="modal">
    <div data-action="click->modal#close" class="fixed z-10 w-full h-full top-0 left-0 bg-black bg-opacity-40"></div>
    <div data-modal-target="sidebar" class="fixed top-0 right-0 z-20 w-1/2 sm:w-3/6 lg:w-2/6 h-full bg-white overflow-y-scroll shadow flex flex-col ease-in-out duration-300 p-5 translate-x-full">
      <p class="cursor-pointer mb-4" data-action="click->modal#close">❌</p>
      <h2 class="font-bold mb-4"><%= t('.title') %></h2>

      <%= render 'shared/form' %>
    </div>
  </div>
<% end %>

app/views/products/show.html.erb
<br>

<%= image_tag @product.photo, width: 200 if @product.photo.attached? %>

<h1 class='title'><%= @product.title %></h1>

<p class='description'><%= @product.description %></p>

<span class='price'><%= @product.price %>$</span><br>

<%= link_to 'Editar producto', edit_product_path(@product) if @product.user_id == Current.user&.id %><br> <!-- Solo lo puede editar el mismo creador -->

<%= link_to 'Eliminar producto', product_path(@product), data:{
    turbo_method: :delete,
    turbo_confirm: t('common.confirm')
} if @product.user_id == Current.user&.id %>  <!-- Por defecto los link_to hacen peticiones GET, debemos cambiarlo --> <!-- Solo lo puede eliminar el mismo creador -->

<%= link_to t('.view_more_products', username: @product.user.username), user_path(@product.user.username) %>

<% if @product.favorites.find_by(user: Current.user) %>
    <%= link_to '💔', favorite_path(@product.id), data:{ turbo_method: :delete } %> 
<% else %>
    <%= link_to '❤️', favorites_path(product_id: @product.id), data:{ turbo_method: :post } %> 
<% end %>